- name: Install a private SSH key
  vars:
    source_key: ./sample.enc.rsa
    dest_key: ~/.ssh/abasille-sample.rsa
  tasks:
  - name: Ensure .ssh directory exists.
    file: 
      dest: "{{ dest_key | dirname }}"
      mode: 0700 
      owner: user 
      state: directory
  - name: Install ssh key
    copy: 
      src: "{{ source_key }}" 
      dest: "{{ dest_key }}"
      mode: 0600
      owner: user
